📌 배열 인덱싱 및 변경

arr.reshape(new_shape)	배열 모양 변경

arr.flatten()	1차원 배열로 변환

arr.transpose()	전치(transpose)

np.concatenate((a, b), axis=0)	배열 연결

np.split(arr, indices_or_sections)	배열 분할


1. arr.reshape(new_shape) 배열 모양 변경

In [9]:
import numpy as np

a = np.repeat(10, 10)
print("a = np.repeat(10, 10)")
print(a)
print()

print("a.reshape(2,5)")
print(a.reshape(2,5))

a = np.repeat(10, 10)
[10 10 10 10 10 10 10 10 10 10]

a.reshape(2,5)
[[10 10 10 10 10]
 [10 10 10 10 10]]


2. arr.flatten() 1차원 배열로 변환

In [13]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print("a = np.array([[1,2,3],[4,5,6]])")
print(a)
print()
print("a.flatten()")
print(a.flatten())

a = np.array([[1,2,3],[4,5,6]])
[[1 2 3]
 [4 5 6]]

a.flatten()
[1 2 3 4 5 6]


3. arr.transpose() 전치(transpose)

In [14]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print("a = np.array([[1,2,3],[4,5,6]])")
print(a)
print()
print("a.transpose()")
print(a.transpose())

a = np.array([[1,2,3],[4,5,6]])
[[1 2 3]
 [4 5 6]]

a.transpose()
[[1 4]
 [2 5]
 [3 6]]


4. np.concatenate((a, b), axis=0) 배열 연결

In [15]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

print("a = np.array([[1,2,3],[4,5,6]])")
print(a)

print("b = np.array([[7,8,9],[10,11,12]])")
print(b)
print()
print("np.concatenate((a, b), axis=0)")
print(np.concatenate((a, b), axis=0))

a = np.array([[1,2,3],[4,5,6]])
[[1 2 3]
 [4 5 6]]
b = np.array([[7,8,9],[10,11,12]])
[[ 7  8  9]
 [10 11 12]]

np.concatenate((a, b), axis=0)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


5. np.split(arr, indices_or_sections) 배열 분할

In [17]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

print("a = np.array([[1,2,3],[4,5,6]])")
print(a)
print()

print("np.`split`(a, 2, axis=0)")
print(np.split(a, 2, axis=0))

a = np.array([[1,2,3],[4,5,6]])
[[1 2 3]
 [4 5 6]]

np.`split`(a, 2, axis=0)
[array([[1, 2, 3]]), array([[4, 5, 6]])]
