📌 배열 생성 관련 함수


np.array(): 리스트/튜플을 NumPy 배열로 변환

np.arange(start, stop, step): 지정 범위의 정수 배열 생성

np.linspace(start, stop, num): 시작~끝 사이를 균등 간격으로 나눈 값 생성

np.repeat(array, repeats, axis=None): 기존 배열의 각 원소를 반복해서 확장

np.tile(vector, reps): 백터 전체 반복

np.zeros(shape)	: 0으로 채워진 배열 생성

np.ones(shape): 1로 채워진 배열 생성

np.eye(N):	단위행렬(identity matrix) 생성

np.empty(shape):	초기화되지 않은 배열 생성 (빠르지만 값은 쓰레기값)

np.full(shape, value):	지정된 값으로 채운 배열 생성


1. np.array(): 리스트/튜플을 NumPy 배열로 변환

In [4]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([[1,2],[3,4],[5,6]])

print("1차원 배열:", a)
print("2차원 배열:")
print(b)


1차원 배열: [1 2 3 4]
2차원 배열:
[[1 2]
 [3 4]
 [5 6]]


2. np.arange(start, stop, step): 지정 범위의 정수 배열 생성

In [8]:
import numpy as np
a = np.arange(1,11)
b = np.arange(1,11,2)

print("1부터 10까지의 a: ",a)
print("1부터 10까지 간격 2 씩의 b: ", b)

1부터 10까지의 a:  [ 1  2  3  4  5  6  7  8  9 10]
1부터 10까지 간격 2 씩의 b:  [1 3 5 7 9]


3. np.linspace(start, stop, num): 시작~끝 사이를 균등 간격으로 나눈 값 생성

endpoint 옵션 - np.linspace(start, stop, num, endpoint = False, True)
(default True)

마지막 값을 포함 시키질지 말지 여부

In [12]:
import numpy as np

a = np.linspace(0,10,3)
b = np.linspace(0,10, 3, endpoint=False)

print("a")
print(a)

print("\nendpoint false의 b")
print(b)

a
[ 0.  5. 10.]

endpoint false의 b
[0.         3.33333333 6.66666667]


4. np.repeat(array, repeats, axis=None): 기존 배열의 각 원소를 반복해서 확장

In [17]:
import numpy as np
a = np.repeat(8, 4)
b = np.repeat(a, 2)

print("np.repeat(8, 4): ", a)

print("np.repeat(a, 2):", b)


np.repeat(8, 4):  [8 8 8 8]
np.repeat(a, 2): [8 8 8 8 8 8 8 8]


5. np.tile(vector, reps): 백터 전체 반복

In [18]:
repeated_whole = np.tile([1,2,4],2)
print("벡터 전체를 2번 반복: ", repeated_whole)

벡터 전체를 2번 반복:  [1 2 4 1 2 4]


6. np.zeros(shape) : 0으로 채워진 배열 생성
7. np.ones(shape): 1로 채워진 배열 생성

In [26]:
a = np.zeros([2,3])
b = np.ones(10)

print("np.zeros([2,3]): ")
print(a)
print("\nnp.ones(10):")
print(b)

np.zeros([2,3]): 
[[0. 0. 0.]
 [0. 0. 0.]]

np.ones(10):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


8. np.eye(N): 단위행렬(identity matrix) 생성


In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. np.empty(shape): 초기화되지 않은 배열 생성 (빠르지만 값은 쓰레기값)

In [28]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

10. np.full(shape, value): 지정된 값으로 채운 배열 생성

In [29]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])